### ISSUE TITLE
Violin split - request for adjustable marker position

### ISSUE THREAD

**Issue by ericmelse** [benjann/violinplot#1]
Dear Ben,

Many thanks for the new option split.
My request is about a related option to be able to adjust the marker position when not a line is used but a symbol.
An example illustrates what the issue is.
```
* Setup
sysuse nlsw88 , clear
gen ln_wage = ln(wage)
egen z_ln_wage= std(ln_wage)
* binary for split example
label define lbl_south 0 "not so" 1 "in south" , replace
foreach var in south {
	ren `var' b_`var'
	label values b_`var' lbl_`var'
	label var b_`var' "by `var'"
}
* Split violin drawing a line for the median and a symbol for the mean
violinplot z_ln_wage , swap gap(0) split(b_south) med(type(l)) mean(type(m) msize(*1.5) msymbol(oh)) ///
	ytitle("ln(wage/GNP deflator) (standardized)", s(*1.1) margin(l-2 r+2)) ///
	plotreg(margin(l+45 r+45)) name(south, replace)
```
Which results in:
![Example_violinplot_nlsw88_z_ln_wage_split_b_south](https://user-images.githubusercontent.com/3686136/203910310-55164574-4179-430e-9afe-72e2463b090f.png)
My 'problem' is with the drawing of each symbel (`oh`) in the area on the opposite half. Ofcourse, we can control the size to prevent this from happening but we will end up with pretty small symbols that might not be visually communicative.
I am thinking of a single parameter that could work both ways, moving the symbols of each half away from the dividing line (bottom of the distribution).
Thus adjusting upward from there for each.
Maybe `pos(0)` as the default and using the usual controls, like `pos(*1.1)` or, alternatively `pos(+.5)` to have the symbol move leftward or rightward respectively (really just upward from the bottom line for each).

**Comment by benjann** [comment]
The requested option is already implemented, I believe. See suboption `offset()` in `split()`. Example:

```
sysuse nlsw88 , clear
gen ln_wage = ln(wage)
egen z_ln_wage= std(ln_wage)
violinplot z_ln_wage, split(south, offset(.2)) ///
    mean(type(m) msize(*1.5) msymbol(oh))  ///
    ytitle("ln(wage/GNP deflator) (standardized)", s(*1.1) margin(l-2 r+2)) ///
    xscale(range(-1 3))
```
![Graph](https://user-images.githubusercontent.com/12543105/203922672-cb7ce256-43a8-4186-8025-6058a3f6f11c.png)

The offset is in units of the categorical axis; each violin typically consumes up to one unit (i.e. a half violin consumes up to half a unit). So an offset around .1-.2 may  make sense.

Also note how I used `xscale()` instead of `plotregion()`. The violin is placed at 1, so `range(-1 3)` adds two units on each side.

For the labels of the split values in the legend there would be option `slabels()` (see `help violinplot`), but I just discovered that I forgot to add the option to the syntax call (although I did add the code implementing the option...). I'll fix that and post an update.

**Comment by ericmelse** [comment]
Ah Ben,
Yes, how good that it is available (I did miss that reading the help file).
And I appreciate the improvement, simplicification, of my example code.

**Comment by ericmelse** [comment]
Dear Ben,
I try to control color in the violin plot and using a 'standard' Stata color works well, like:
```
* Setup
sysuse nlsw88 , clear
gen ln_wage = ln(wage)
egen z_ln_wage= std(ln_wage)
violinplot z_ln_wage, vertical col(pink%75*1.45) fill box(type(l) stat(p20 p80)) ///
    med(type(l)) mean(type(m) msize(*1.5) msymbol(oh))  ///
    ytitle("ln(wage/GNP deflator) (standardized)", s(*1.1) margin(l-2 r+2)) ///
    xscale(range(-1 3))
```
Which results in:
![Example_violinplot_nlsw88_z_ln_wage_pink](https://user-images.githubusercontent.com/3686136/203930667-ae8306d6-962b-4d5f-a70d-47d0bb552f09.png)
But, when I try to use RGB values, like:
```
violinplot z_ln_wage, vertical col("204 102 157") fill box(type(l) stat(p20 p80)) ///
    med(type(l)) mean(type(m) msize(*1.5) msymbol(oh))  ///
    ytitle("ln(wage/GNP deflator) (standardized)", s(*1.1) margin(l-2 r+2)) ///
    xscale(range(-1 3))

```
or like:
```
violinplot z_ln_wage, vertical col("204 102 157%70") fill box(type(l) stat(p20 p80)) ///
    med(type(l)) mean(type(m) msize(*1.5) msymbol(oh))  ///
    ytitle("ln(wage/GNP deflator) (standardized)", s(*1.1) margin(l-2 r+2)) ///
    xscale(range(-1 3))

```
then I get an error message:
```
color specification '204' is invalid
r(3498);

```

**Comment by benjann** [comment]
Thanks for reporting. I believe the problem is that the outer quotes are stripped during syntax parsing. I will fix this and post an update.

**Comment by benjann** [comment]
The latest update now fixes both problems. Option `slabels()` now exists and options such as `color()`, `lcolor()`, etc. now allow color specifications that use double quotes.
