### ISSUE TITLE
Drawing of a relevant number of rags, not all of them

### ISSUE THREAD

**Issue by ericmelse** [benjann/violinplot#4]
Dear Ben,

Using `violinplot`, it is possible to draw below or above the distribution curve a rug of the cases by their measurement value. This is a most useful option. However, when large data sets are used, e.g. of a survey, the number of cases can get very large and with that the number of rugs increases with it. This can lead to very large graph files. In particular SVG files quickly grow in size due the amount of objects that are included. For example, a single rug of my example produces a SVG file of 4,576KB while a file with 'flagged' rugs is 1,783KB. A 61% reduction in file size is maybe not that much but it is certainly practical when multiple violins are combined in a graph and when we are dealing with even larger data sets (which I indeed do).
So, I will try to explain my point with the following example for which I use my own data. In this case the annual salary of 30.000 working professionals in The Netherlands. That data was log transformed, centered and bounded between 0 and 1 for this example. Github will not allow me to upload a dta file, so, I will email that to you.

The code to draw the distribution using `violinplot`, including 30.000 rags, is:
```
use "NSO21_Example_Salary.dta" , clear
violinplot bd_zs_lnMsalYer21 , n(200) left rag(mc(%20) off(-.03)) nowhisk nobox nomed ///
   ysc(off) xsc(noex) xtit("") name(violin, replace)
```
which results in:
![Rag_violin](https://user-images.githubusercontent.com/3686136/205326993-4f561ba7-0788-4811-94ac-492d74e58cd1.png)

Next, I proceeded with coding to get a so-called 'flag' variable to control the drawing of only those cases that have a unique value for which a rag symbol has to be drawn. The logic of this is that drawing more than one symbol on a particular measurement scale makes not much sense. The distribution curve itself makes the occurence of cases per measurement value clear. The rags should visualize the density of measurements along the scale, which we expect to gradually thin out at the extreme ends. Using a color with reduced opacity supports the presentation of this density when a lot of unique cases are in the data (like with my example data set).

Just to be complete, here is my code to determine the flag variable and the offset yaxis position to imitate the `violinplot` result:
```
local var zs_lnMsalYer21
gsort `var' // this MUST be done
egen flag = tag(`var')
gen offset = -.18 if flag==1 // adjusting yaxis flag position
```
The code to draw the distribution using `tw kdensity`, including 11.652 rags, is:
```
use "NSO21_Example_Salary.dta" , clear
ren yva0 offset
tw (kdensity bd_zs_lnMsalYer21, n(200))(scatter yva0 bd_zs_lnMsalYer21 ///
   if flag==1, m("|") mc(navy%20) msize(*1)) ,  ///
   ysc(off) xsc(noex) ylab(none) ytit("") legend(off) name(tw, replace)
```
which results in:
![Rag_twoway_flag_20221201](https://user-images.githubusercontent.com/3686136/205326774-e8ce749b-7666-41a1-987f-8beb59c5ee57.png)

I hope that you can agree with my view that drawing 'flagged' rags, when large data sets are used, is a sufficient proposition to present the cases with a unique value on the measurement scale.
Maybe you could introduce a new option for `rag` that applies the flagging of the cases with a unique value instead of using all of them. Possibly you might call this option `flag`.

**Comment by benjann** [comment]
Hi Eric, I agree, a `unique` supoption to `rag()` would be useful (or even set this as default?). ben

**Comment by benjann** [comment]
The latest update now features  `rag(unique)`. This will only print one marker per unique value.

**Comment by ericmelse** [comment]
Dear Ben, many thanks for this update. It works very well indeed:
![Rag_violin_new](https://user-images.githubusercontent.com/3686136/205428194-1787d88f-7ef1-4f58-84da-88f2e18645a2.png)
Like with my own `tw kdensity` example, above, when I export the graph in SVG format, the file size is now 1,781KB, instead of 4,576KB, so we achieve the same reduction. That should also speed up drawing in Stata's graph window.
