### ISSUE TITLE
Option request: set seed for marker points

### ISSUE THREAD

**Issue by ericmelse** [benjann/violinplot#5]
Dear Ben,

Thank you so much for the recent update of `violinplot` (version 1.1.9).
In particular the ability to add markers for data points is very welcome and usefull indeed.
Here is an example of what I can accomplish (after a lot of heavy code lifting and using `graph combine` as I am combining an unary violinplot with multiple binary violinplots), using my own research data:
![NSO23_Dstat_Salary_Figure_0x14s_20240317](https://github.com/benjann/violinplot/assets/3686136/00cadc99-f4d6-4f21-ae18-ac57dbdd86ad)
Sophisticated as it already is, I do have an option request:

**Option to set the seed**
I am rather picky about the replication of results, also when it is about unique markers for repeated data points. However, each time I create the same plot, different unique markers are selected, like:
![NSO23_Dstat_Salary_Multiple_Runs_20240317](https://github.com/benjann/violinplot/assets/3686136/fa735630-e51a-4a75-96eb-4f60069d44c4)
Time permitting, I suppose including an option like `rag(u seed(2024))` would be sufficient, assuming that you can incorporate such seed number in the code that determines the position of the (unique) markers.

Best,
Eric

**Comment by benjann** [comment]
Hi Eric,

simply apply `set seed` at the top of the do-file. The graphs will then replicate exactly.

I will probably not add a `seed()` suboption, but I will add a note to the documentation that you need to set the seed if you want results from `rag(spread())` to be reproducible.

ben

**Comment by ericmelse** [comment]
Dear Ben,
Handsome `set seed 2024` and a 'general' approach as usually!
Here is my test result (just to complete the example):
![NSO23_Dstat_Salary_Figure_0x15s_0x16s_20240317](https://github.com/benjann/violinplot/assets/3686136/d5df2505-eaeb-4f64-ad53-4ca43f0e1cf1)
